# Metadata
title: 'Meetups & Conferences'
description: "Notes from the various meetups and conferences I attend."
url: "http://meetups.pixelastic.com/"

# Build
source: ./src
destination: ./dist
baseurl: ""

# Pagination
paginate: 5

# Tags
tag_page_layout: tag
tag_page_dir: tags

# Archives
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'


# Algolia
algolia:
  application_id: 'O3F8QXYK6R'
  index_name: 'meetups'
  read_only_api_key: '6a027258345c8a569385505b041e6dec'


# author:
#   name:           'Timothée Carry'
#   url:            https://twitter.com/pixelastic
# github:
#   repo:           https://github.com/pixelastic/meetups.pixelastic.com

# # Build
# timezone:         "Europe/Paris"
# encoding:         "utf-8"

# markdown:         redcarpet
permalink: pretty


