title:            'Meetups'
description:      "Notes from the various meetups and conferences I attend"
url:              http://meetups.pixelastic.com
base_url:         meetups.pixelastic.com
source: "app"
author:
  name:           'Timothée Carry'
  url:            https://twitter.com/pixelastic

# Dependencies
markdown:         redcarpet
plugins:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup


paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/pixelastic/meetups.pixelastic.com

# Build
timezone:         "Europe/Paris"
encoding:         "utf-8"

# Algolia
algolia:
  application_id: 'O3F8QXYK6R'
  index_name: 'meetups'
