# Metadata
title: 'Meetups & Conferences'
description: "Notes from the various meetups and conferences I attend."
url: "http://meetups.pixelastic.com/"

# Build
source: ./src
destination: ./dist
baseurl: ""
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 5

# Algolia
algolia:
  application_id: 'O3F8QXYK6R'
  index_name: 'meetups'
  read_only_api_key: '6a027258345c8a569385505b041e6dec'


# author:
#   name:           'Timothée Carry'
#   url:            https://twitter.com/pixelastic
# github:
#   repo:           https://github.com/pixelastic/meetups.pixelastic.com

# # Build
# timezone:         "Europe/Paris"
# encoding:         "utf-8"

# markdown:         redcarpet
permalink: pretty


