version: 2.1

orbs:
  node: circleci/node@5
  ruby: circleci/ruby@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
    steps:
      - checkout

      # Add SSH key
      - add_ssh_keys:
          fingerprints:
            - "SHA256:I73ETs/VuuUA2z6GexfJ0q4U7GLwjY8jZlC15uq/aMw"

      # Install Ruby dependencies
      - ruby/install-deps

      # Install Node dependencies
      - node/install-packages:
          pkg-manager: yarn

      # Store both Ruby and Node dependencies in cache
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
            - node_modules

      # Run deploy script
      - run:
          name: Deploy
          command: yarn run deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
