version: 2.1

orbs:
  node: circleci/node@5
  ruby: circleci/ruby@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:I73ETs/VuuUA2z6GexfJ0q4U7GLwjY8jZlC15uq/aMw"
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
            - node_modules

      - run:
          name: Write Algolia API key
          command: echo $ALGOLIA_API_KEY > _algolia_api_key

      - run:
          name: Deploy
          command: yarn run deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
